### ISSUE TITLE
Perl 6 support

### ISSUE THREAD

**Issue by sarna** [Jaredk3nt/nova-theme#1]
Hi, would it be possible to add support for Perl 6? I absolutely love this theme, but with Perl 6 it's kind of broken :(

**Comment by Jaredk3nt** [comment]
Definitely @sarna, if you could leave me with some example code so I could get the highlighting right!

**Comment by sarna** [comment]
Sure @Jaredk3nt, here's the code from the famous [blog post](https://www.evanmiller.org/why-im-learning-perl-6.html)
in vim:
![nice](https://user-images.githubusercontent.com/32620681/43360213-aed679f0-92b1-11e8-87c3-92c48fc20b9a.png)
and in vscode with your plugin:
![broken](https://user-images.githubusercontent.com/32620681/43360228-00f11722-92b2-11e8-93e9-a609582b7422.png)

**Comment by Jaredk3nt** [comment]
Added in v1.2.1

Colorizing for Perl was a bit weak in VS Code if I'm being honest, but I did the best I could

**Comment by sarna** [comment]
Perl6 language support is wonky in VS Code, that's why :)
Thanks anyway, it looks good now!
